- name: Download Zabbix Repository Package
  get_url:
    url: https://repo.zabbix.com/zabbix/{{ zabbix_version }}/release/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest_{{ zabbix_version }}+ubuntu{{ ubuntu_version }}_all.deb
    dest: /tmp/zabbix-release_latest_{{ zabbix_version }}+ubuntu{{ ubuntu_version }}_all.deb
- name: Install Zabbix Repository Package 
  apt:
    deb: /tmp/zabbix-release_latest_{{ zabbix_version }}+ubuntu{{ ubuntu_version }}_all.deb
    state: present
- name: Update apt cache
  apt:
    update_cache: yes